### ISSUE TITLE
Convert `@redwoodjs/web` to TypeScript

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1217]
The current package has type definitions contributed by @Burnsy, but we would like to convert the entire package to TypeScript.

- [x] Convert project to transpile TS and JS files. @peterp #1232 
- [x] Convert `RedwoodProvider`(in progress #1291)
- [x] Convert `FatalErrorBoundary`(in progress #1273)
- [x] Convert `createGraphQLClient`
- [x] Convert `GraphQLProvider`
- [ ] Convert `FlashComponent` (in progress #1312)
- [ ] Convert `src/packages/web/config.js` (in progress #1312)
- [ ] Remove `allowJs` from tsconfig in web package.

/cc @kimadeline

**Comment by Burnsy** [comment]
Maybe flash should be it's one module as it can be quite useful without the forms. 😌 ie for notifications.

**Comment by peterp** [comment]
It's so difficult to strike a balance here, maybe we can just keep it in.

**Comment by thedavidprice** [comment]
TeamTS FTW 🚀

**Comment by peterp** [comment]
Whoops, we need to open this again, since we need to convert the `Flash` component.

**Comment by Krisztiaan** [comment]
#1824 for the flash component. #1312 is not relevant anymore.

**Comment by Krisztiaan** [comment]
#1641 resolved "Convert `src/packages/web/config.js`"
