### ISSUE TITLE
Support Azure AD authentication

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/redwood#1310]
This issue seeks to support Azure AD as authentication.

### Todo
- [X] Create `azureAd` AuthProvider (#1311)
- [X] Create `azureAd` auth generator with auth template (#1311)
- [X] Example `azureAd` auth in the `playground-auth` repository (https://github.com/redwoodjs/playground-auth/pull/6)
- [X] Initial documentation  in the `redwoodjs.com` repository (https://github.com/redwoodjs/redwoodjs.com/pull/407)
- [x] Add `AzureAdUser` decoder
- [x] Add JWT validation in the decoder (https://github.com/redwoodjs/redwood/pull/1311#discussion_r502886525)
- [x] Grab `roles` from the claim if possible (https://github.com/redwoodjs/redwood/pull/1311#discussion_r502887345)
- [x] ~Implement `yarn rw setup auth <azureAd>` and follow deprecation of `yarn rw g auth ...` (as of #1307 & #1309)~
- [x] Some more work on the documentation

### Request/Questions
- 1. Tests? (where?)
- 2. Test and validation from core team and community

### Changes in packages
- `@redwoodjs/auth`
- `@redwoodjs/api`
- `@redwoodjs/cli`

### Implementation
* [AuthProvider & Generator](https://github.com/redwoodjs/redwood/pull/1311): #1311 (merged ✅)

* [Documentation](https://github.com/redwoodjs/redwoodjs.com/pull/407) (merged ✅)

* [Example](https://github.com/redwoodjs/playground-auth/pull/6) (merged ✅)

### Documentation
* [Initialize client applications using MSAL.js](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications)

* [MSAL's UserAgentApplication class](https://pub.dev/documentation/msal_js/latest/msal_js/UserAgentApplication-class.html#constructors)

* [Azure Active Directory: Application Roles](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles)

 Please let me know your overall feedback or code review in respective PRs. Thanks!

**Comment by thedavidprice** [comment]
Woah, this is amazing @jeliasson Thank you for the huge lift to get this going!

Our primary AuthMaster9000™, Peter, is on vacation and won't be back until next week. He's going to be slammed, but I'll get this on his radar.

@dthyresson might you feel comfortable taking a look at these 3 PRs in the meantime? At a minimum, I know you could field questions and provide direction. And if you're comfortable with a full review as well, then I'm all for it! Let me know.

## Migration `yarn rw g auth [providers]` to `yarn rw setup [command]`
At today's Meetup I started the process of migrating these Auth generators to the new Setup command.
- https://github.com/redwoodjs/redwood/issues/1307
- https://github.com/redwoodjs/redwood/pull/1309

The primary missing setup in my PR is step 2 — figuring out how to keep things DRY but also make each provider option into a separate command (per Setup proposal). 

Ideally, this PR would add Azure Auth to Setup so we can avoid immediately turning around and migrating it from `rw g auth ...`. But I'm not sure when I'll be able to finish PR #1309 and what the current status of "completeness" is on these current PRs.

What say you both, @jeliasson and @dthyresson?

**Comment by jeliasson** [comment]
Thanks for the feedback @thedavidprice 🎉

I missed yesterdays meetup and joined in just when you guys were about to round off. It's now early morning, so a perfect time to grab another cup of ☕ and tune in to that session on Youtube and get the latest scoops (among `yarn rw setup`). I'm sure we can align this PR with the works in #1309.

@dthyresson @peterp 
When you guys have a chance to look at this, let me know if you need a dummy Azure organizational account or similar. In the meantime, I'll look into the JWT validation and `yarn rw setup`.

**Comment by andrew-hwahin** [comment]
Thank you @jeliasson for implementing the Azure authentication into RedwoodJS! 🙏

Can't wait to use it! 🤩

**Comment by jeliasson** [comment]
@dthyresson 
All related PR's is merged and you can move the [project card](https://github.com/redwoodjs/redwood/projects/6#card-48931457) to Done and close this issue if you'd like. Thanks!

**Comment by dthyresson** [comment]
> can move the project card to Done and close this issue if you'd like.

Looks like someone already did. Thanks!
