### ISSUE TITLE
[Meta] Support for mobile

### ISSUE THREAD

**Issue by pepibumur** [redwoodjs/redwood#1623]
I was encouraged by @thedavidprice to move the support for mobile forward so I'm fleshing out an implementation plan in this issue.

### 1. **Init**
We need to extend the initialization workflow to create the mobile side. I suggest building an opt-in feature. I'm not entirely familiar with the implementation of that workflow but I guess we can extend it with some argument or prompts during the process. The command would create a mobile directory with the standard structure of a React Native application. The mobile side would be part of the Yarn workspace defined at the root, like it's done for the `web` and `api` sides:

```
mobile/
  package.json
  index.js
  App.js
  src/
  ios/
   Podfile/
    ...
  android/
    ...
```

#### Open questions
- Do we hide the configuration files (Metro, Jest)?
  - I'd to hide them originally and expose APIs as needed. Metro is like Webpack, if you expose the entire API to developers there's an increased likelihood of developers introducing complexity and potentially conflicting with the framework.
 - Do we want to provide default packages?
   - I'd include [React Nativation](https://reactnavigation.org/)
 - If we include React Nativgation, should we wrap it inside `@redwoodjs/mobile`?
   - I think so, it's the same as RedwoodJS providing the routing for web. If we decide the implementation, we can optimize it and improve the developer experience easily.
 - Do we provide a GraphQL client?
   - Yes! I'd add Apollo. The question here is again the same. Should we wrap it inside `@redwoodjs/mobile`? Or even further, should we aim for reusing the client for web?
 - Do we install CocoaPods if it's not installed?
   - Until we can remove the [friction](https://github.com/react-native-community/discussions-and-proposals/issues/318) introduced by CocoaPods, the initialization of the mobile side will require having CocoaPods installed, and running the `pod install` command. The question is how should the creation flow handle the scenario where CocoaPods is not installed? Should we install it ourselves? Should we fail the initialization and let the user know that they need CocoaPods?
   
 
### 2. **Build**
Since there's a new side, we need to extend the build command to build the mobile side too. I think the interface could be something along the lines of:

```bash
rw build mobile # builds ios and android native, and js
rw build mobile ios # builds only iOS native (Compilation with Xcode)
rw build mobile android # builds only Android native (Compilation with Gradle)
rw build mobile js # builds only JS (transpilation with MetroJS)
```

### 3. **Test**
Similarly, we'd need to extend the `test` command to account for mobile:

```bash
rw test mobile # tests ios and android native, and js
rw test mobile ios # tests only iOS native (using Xcode)
rw test mobile android # tests only android native (using Gradle)
rw test mobile js # tests only JS (using MetroJS)
```

### 4. **Dev**
Then we should extend the `rw dev` command to be able to run the `mobile` and the `api` side. It's important that we own the initialization of the network stack in the app to make sure it points to the right URL. When the app is run locally, the network client needs to point to the locally-running instance of the `api` side.

```
yarn dev mobile
```

## Future areas of work
- **Remove CocoaPods:** We can either contribute to the [official CLI](https://github.com/react-native-community/discussions-and-proposals/issues/318) or execute the idea proposed on that issue on the RedwoodJS side. That'll remove a lot of indirection from having to have a Ruby and CocoaPods environment, and therefore improve the developer experience.
- **Deployment:** Unlike a web or an API side, for which we have services like Netlify that builds and deploys them, in the case of mobile developers have traditionally resorted to client-side automation through programmable-DSLs like [Fastlane](https://fastlane.tools). I think redwood could provide at least a command for archiving the app for release, and then letting a server-side service or CI pipeline to sign and upload it to the right channel (e.g. App Store / Google Play)

### Tasks
- [ ] Vendor template into the create-redwood-app package https://github.com/redwoodjs/redwood/pull/1637
- [ ] Write up a tutorial for building a mobile side
- [ ] Extend `init` to include the mobile side
- [ ] Extend `build` to account for the mobile side.
- [ ] Extend `test` to account for the mobile side.
- [ ] Add setup task to add the mobile side to an existing project.

**Comment by thedavidprice** [comment]
@pepibumur huge thank you for getting this rolling! Looping in @peterp and also @aldonline for visibility. And will bring this up at our next internal meeting.

The above categories look good. Most of our current commands already take Sides as an option and default to both api + web. But, as you've indicated above, you can currently specify a side or sides: `yarn rw dev api` or even `yarn rw dev api web`.

### Init
Good idea for this to be an option that's passed at time of installation. We'll also want to add a `setup` command for adding a new side to a project, e.g. `yarn rw setup side-mobile`.

> Do we hide the configuration files (Metro, Jest)?

Our current strategy is to 1) hide and 2) provide a way for developers to extend and override as needed. Redwood is big on handling the config so you don't have to. But when you _do_ need to, there's a way to do so.

> Do we want to provide default packages?

How about working backward via a kind of mental Tutorial Driven development — when we create a Tutorial for people to learn the Mobile Side of Redwood, what will they need to go from zero to having a working, running, local app? Hopefully, this helps guide toward decisions about what to include or not.

I don't know React Native dev so I can't speak to which packages are more or less standard vs others. We've been careful not to enforce opinion about things (e.g. state) where there's no current "winner". Even in the case of Apollo Client, which ships with Redwood, it's now swappable.

> If we include React Nativgation, should we wrap it inside @redwoodjs/mobile?

Again, not my wheelhouse. In general, we've done as you mention above — include in a Redwood package and add some special sauce where we can to improve DX.

> Do we provide a GraphQL client?

Ah, would be interesting if we can re-use and then also make it swappable?

> Do we install CocoaPods if it's not installed?
 
Coca-whaaa? 😆 

Maybe this is another "What's the Tutorial need for a golden path experience?"

**Comment by peterp** [comment]
Hey Pedro!

I would love to chat to you about "sides" and how I envisioned hooking in the `rw dev/ rw build/ rw test` commands into the project. I think that would form a good foundation for integration of the mobile side, as well as any other sides in the future.

> Do we hide the configuration files (Metro, Jest)?
> I'd to hide them originally and expose APIs as needed. Metro is like Webpack, if you expose the entire API to developers there's an increased likelihood of developers introducing complexity and potentially conflicting with the framework.

I think I can count on my 1 finger the amount of times I've had to touch the metro configuration (directory-named-plugin). I think it's fine to hide these. I am super-duper cautious of the upgrade path for react-native users though. Post v60 it was OK, but I think this is probably my most major concern.

> Do we want to provide default packages?

I would suggest creating a `@redwoodjs/mobile` package that includes a navigation library. I've personally preferred `wix-native-navigation`,  but it has not always been smooth sailing. I think react-navigation now has a native driver..., but it took them several years of fudging to get to the point.

> Do we provide a GraphQL client?
> Yes! I'd add Apollo. The question here is again the same. Should we wrap it inside @redwoodjs/mobile? Or even further, should we aim for reusing the client for web?

We could create `@redwoodjs/data` and then make that a dependency of web/mobile.

> Do we install CocoaPods if it's not installed?

I think we should prompt users to install it when it's required to be installed. I think when a user runs `yarn rw dev mobile` then we can run `pods install` and if that isn't available we can prompt them to install it.

**Comment by peterp** [comment]
Here's the RFC for sides: https://github.com/redwoodjs/redwood/issues/1626

**Comment by pepibumur** [comment]
> I would love to chat to you about "sides" and how I envisioned hooking in the rw dev/ rw build/ rw test commands into the project. I think that would form a good foundation for integration of the mobile side, as well as any other sides in the future.

I like the idea of modeling the sides, especially considering that your plan is to add support for mode sides to the project.

### Init
I'll then add an argument to opt into generating the mobile side. I also added a task at the top to add a setup task. I think this will be useful for the projects that are already using Redwood and might want to add the mobile side.

### Hiding configurations
I'll start by hiding them and expose them as needed. I've seen those files becoming a huge source of complexity so I'd prefer Redwood to own and optimize them.

### Default packages

> How about working backward via a kind of mental Tutorial Driven development — when we create a Tutorial for people to learn the Mobile Side of Redwood, what will they need to go from zero to having a working, running, local app? Hopefully, this helps guide toward decisions about what to include or not.

Good idea. I'll focus on creating that tutorial first and that'll give me ideas about what makes sense to include as default. I noticed RedwoodJS doesn't have a lot of strong opinions, but just a few that I believe are necessary. I think the same applies to mobile. There are certain libraries for which it makes sense for RedwoodJS to be opinionated.


### @redwoodjs/mobile

I like this idea. I think after designing the tutorial that @thedavidprice suggested, I'll have a better idea of what are the most suitable defaults for Redwood. 

### @redwoodjs/data

Like this idea! I think GraphQL client is a good example of a piece that can be reused across sides. The question that I have though is whether the caching components are reusable. In the case of React Native they might depend on some native implementation for IO.

### Pod install

Sure! I think when running the side we can detect whether it requires the installation of pods and we could then run it for them.

**Comment by thedavidprice** [comment]
This is a high priority once we've reached Redwood v1.0.0.

Draft PR for reference #1711

**Comment by thedavidprice** [comment]
Also see discussion in #528

**Comment by Philzen** [comment]
Hey @thedavidprice i just stumbled over this and wondered why it was "closed as completed"? That would tell me that it's now possible to also have a mobile side out-of-the-box., however the linked PR was not merged and #528 was closed in favour of this one, but i cannot find anything in the docs regarding this.

Over there i can read

>  It's not on the v1 roadmap. But it's top of the list afterward.

If that's the case, we should keep an issue open somewhere and have it linked to all relevant PRs and issues mentioned here – or otherwise close with a note "won't do" and why, just so people are in the clear.

**Comment by orta** [comment]
This conversation lives in https://community.redwoodjs.com/t/redwoodjs-and-react-native/3339 ATM
