### ISSUE TITLE
Outstanding Test and Lint Issues [umbrella Issue]

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#259]
### ESLint
- [x] ‘yarn lint’ warnings due to Babel plugin error: #258 

### Jest Coverage
In general, we simply need more test coverage. But for now let’s focus on adding initial tests to packages. Current audit of package mocks and tests:
- [x] **api**: tests and mocks
- [x] **cli**: tests and mocks
- [ ] **core**
- [ ] **create-redwood-app**
- [ ] **dev-server**
- [ ] **eslint-config**: _how/if to test?_
- [ ] **eslint-plugin-redwood**: _how/if to test?_
- [x] **internal**: tests
- [ ] **router**
- [ ] **web**

**Comment by thedavidprice** [comment]
@AryanJ-NYC looping you in on this one as well. Peter just fixed the ESlint issue today, which might be a good PR to explore toward understanding more about backend config. Issue here with link to PR #258 

Last note, isn’t it amazing how much config work is required to make the CRA app “just work”? Definitely not to be taken for granted. So thanks for the help!

**Comment by thedavidprice** [comment]
Progress is happening here. At this time, this Issue isn’t necessary to organize the effort.
