### ISSUE TITLE
Checklist to get Tutorial Working

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#28]
* [ ] Scaffold generator #27 @cannikin
* [ ] No `index.js` required for a Cell
* [x] No `import` required for pages in Router (in progress, @mojombo)
* [ ] No resolvers required in SDL files (in progress, @peterp)
* [ ] Include form helpers from `example-blog` into `redwood` proper
* [ ] Automatically run `yarn install` after `redwood new` is finished building app structure
* [ ] Get hot reloads working again

**Comment by mojombo** [comment]
Auto-importing in Routes is done, I'm just working on some optimizations, but the Tutorial will work fine with what's already in.

**Comment by cannikin** [comment]
Moved to individual issues
