### ISSUE TITLE
New e2e tests tracking issue

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#3118]
Our e2e tests have been a huge source of frustration, confusion and even hatred. This lead to the dark side. Sad.

We're doing e2e tests wrong, so we're going to throw them away and do something better.

We need to test the full development experience, and to ensure that we don't break anything we need an example application that uses most of the parts of the framework. The most complete app we have is `example-blog`

The project should have the following on the API side:
- [ ] GraphQL
- [ ] Services.
- [ ] Services: Auth (DbAuth)
- [ ] Services: Scenarios.
- [ ] Services: BeforeResolvers.
- [ ] Logging.
- [ ] Other "Serverless functions".
- [ ] _... anything else?_

The project should have the following on the WEB side:
- [ ] Auth (DbAuth)
- [ ] Logged in/ logged out states.
- [ ] Scaffolds to create, edit, update and delete things.
- [ ] Scaffolds errors.
- [ ] TailwindCSS.
- [ ] Tests
- [ ] Storybook mocks
- [ ] Prerendering
- [ ] Forms
- [ ] _... anything else?_

Once we have a project that has _all the things above_ then we can click around in it with Playwright to make sure the integration between (api) database -> services -> graphql -> (web) graphql client -> cells is working.

Separately we can test the "design time/ development" experience and make sure that the following commands are working:
`yarn rw test | sb | build | dev | serve` are working correctly. Perhaps we need to test the happy and sad paths here.

**Comment by peterp** [comment]
Related: #3071

**Comment by dthyresson** [comment]
@thedavidprice and @jtoar This seems like a v2 issue to rework the e2e suite, no? Should I change the labelling?

**Comment by thedavidprice** [comment]
This work can happen at any time and is a higher priority. On my radar. Please do leave it as is for now.
