### ISSUE TITLE
🎉 Upgrade Prisma to 2.0.0-beta: tracking issue

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#365]
Today Prisma released the first beta for Prisma v2. We'll need to take our time to integrate, test, and add feature support (which will require discussion):
- **Beta.1** https://github.com/prisma/prisma/releases/tag/2.0.0-beta.1
- **Beta.2** https://github.com/prisma/prisma/releases/tag/2.0.0-beta.2

Community help greatly appreciated. For an example of how we upgraded previous Prisma releases, see #350 

## Renaming the `prisma2` CLI
> With Prisma 2.0 being the default for new developers getting started with Prisma, the command is changed to just prisma. The exising prisma command of Prisma 1 is renamed to prisma1.

## New syntax for defining relations
> The Beta release introduces a new relation syntax which makes the @relation attribute required in each relation in the Prisma schema.
> Additionally, for one-to-one and one-to-many relations, you need add a relation scalar field to the model which is used in the @relation attribute.

**Related**  
- [ ] RWJS Generator support (or no support) for multi-field IDs #323
- [ ] SDL generator ignores relations #324
- [ ] Scaffold generator ignores relations #327
- [ ] Relation Support #316 

## The prisma2 npm package is deprecated
- [x] Done via #350

**Comment by peterp** [comment]
This is already done.
