### ISSUE TITLE
Serverless Framework Integration: Tracking Issue

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3686]
**Audit of current issues and requirements:**

See new tracking board here: https://github.com/orgs/redwoodjs/projects/7/views/1

- [x] https://github.com/redwoodjs/redwood/issues/3284
- [x] https://github.com/redwoodjs/redwood/pull/3782
- [x] https://github.com/redwoodjs/redwood/pull/3755
- [ ] Add cloudfront plugin / some other plugin to deploy the web side
<details>
<summary>**Investigate setting up cloudfront cdn** Expand for details</summary>
- [ ] Add support for serverless CI/CD

#### Adding Cloudfront
Here are the docs for Cloudfront configuration, which will need to be added to the `serverless.yml`:
- https://www.serverless.com/framework/docs/providers/aws/events/cloudfront

Additionally, this will need to be included in the deployment steps:
- yarn `yarn rw build` (includes Web/)
- package up the `web/dist` files (probably zip or tarball)
- deploy packaged file to s3
- configure cloudfront to point to the s3 bucket

I didn't read through the Cache policies — effectively the deployed assets should stay live until the next deployment, at which time all previous should be invalidated.

#### Updating `yarn rw deploy ...`
Lastly, the Redwood deploy command will need to be updated to include the web/dist files on Cloudfront. That command lives here:
https://github.com/redwoodjs/redwood/blob/f359de4059f6b78226e332424447b637fba163e0/packages/cli/src/commands/deploy/aws.js

</details>

- [ ] Check if serverless v3 cli works, and if we should upgrade to it
- [ ] Serverless CI/CD integration
- [x] Resolve TypeScript issues https://github.com/redwoodjs/redwood/issues/3217

---

Out of scope
<details>
<summary>Issues out of scope for v1 integration</summary>

**Consider other hosting providers to target (beyond AWS)**
- https://github.com/redwoodjs/redwood/issues/615

</details>

**Comment by virtuoushub** [comment]
👋🏻  @thedavidprice, I would love to work on this integration.

I looked through the linked issues, is there anywhere you'd like me to start?

**Comment by virtuoushub** [comment]
@thedavidprice - are we looking to update both of these commands?

* https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/aws-providers/serverless.js
* https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/deploy/providers/aws-serverless.js

**Comment by virtuoushub** [comment]
Also, are there any recommended ways to test commands like setup/deploy?

**Comment by virtuoushub** [comment]
In terms of `@netlify/zip-it-and-ship-it` -> `@vercel/nft`, I have found there is more worked needed with `@vercel/nft`. We will need to zip up that command's output, as well as maybe specific the main file? Is there an existing workflow you use that I am able to leverage? Otherwise I might advise sticking with `@netlify/zip-it-and-ship-it` for now.

**Comment by thedavidprice** [comment]
> are we looking to update both of these commands?
> 
> * https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/aws-providers/serverless.js
> * https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/deploy/providers/aws-serverless.js

^^ Yes please!

> Also, are there any recommended ways to test commands like setup/deploy?

^^ We are working on a better answer to this. Let's address it last. Do watch the Chakra-UI setup PR as we're trying to answer the question for that PR as well.

> In terms of @netlify/zip-it-and-ship-it -> @vercel/nft, I have found there is more worked needed with @vercel/nft. We will need figure out how to zip up that command's output per function(as well as maybe specify the main file for that function?).
>
> Is there an existing workflow you use that I am able to leverage? Otherwise I might advise sticking with @netlify/zip-it-and-ship-it for now.

^^ Ok, let's leave it as is for now. But as a TO DO on the PR, let's keep this as an item to research. We have a close relationship with the Vercel team and could possibly get their help. It really is a major improvement over ZiSi and would be worth it as an additional step to improve once the core requirements are working.

**Comment by thedavidprice** [comment]
@virtuoushub #3723 is a fix for TS tracking issue. But there's a lot more work to be done here, specifically outlined in this comment:
https://github.com/redwoodjs/redwood/issues/3284#issuecomment-922375958

Would you like to keep working on these next steps? No pressure either way.

**Comment by virtuoushub** [comment]
> @virtuoushub #3723 is a fix for TS tracking issue. But there's a lot more work to be done here, specifically outlined in this comment: [#3284 (comment)](https://github.com/redwoodjs/redwood/issues/3284#issuecomment-922375958)
> 
> Would you like to keep working on these next steps? No pressure either way.

@thedavidprice, Yes sounds good, I had as `TODO` for that other ticket:

> Still need to figure out the flow to swap out @netlify/zip-it-and-ship-it for @vercel/nft as their behavior is slightly different.

The context you provided is enough for me to start tackling #3284 

In terms of #615 what are your thoughts about the acceptance criteria for that?

**Comment by Irev-Dev** [comment]
Let me know if there's something you'd like me to help with.

**Comment by thedavidprice** [comment]
@virtuoushub Good question about #615 — probably nothing additive there; I just grabbed it because it was a related open issue. And a good reminder that Serverless framework can be used for a lot of hosting providers. For now, let's focus on AWS only. (But open to more options given interest, just know that we'll hit issues with non-AWS Lambda compatible function handlers.)

I really do think it's going to be a big improvement to switch from Zip-it-and-ship-it to Vercel's nft. @Irev-Dev maybe that's a place for you to help with research. Also, we can loop in folks from Vercel if/as needed once we know the questions to ask. 

Thanks all!

**Comment by virtuoushub** [comment]
> Let me know if there's something you'd like me to help with.

@Irev-Dev happy to have your help, will tag you on related PRs.

For switching from `@netlify/zip-it-and-ship-it` for `@vercel/nft`; what might help is figuring out how to zip up `nft` command's output per function, as well as specify the main file for that function.

From my testing, we kind of have to reverse engineer what is happening in `@netlify/zip-it-and-ship-it` and make sure that happens when we call `@vercel/nft` as this new command does a subset of the old, and does so in a way that does not result in the same file/directory output.

**Comment by Irev-Dev** [comment]
I've had a quick read of ntf and had gathered that it didn't do the zipping. 

I'm a bit lost on the motivation for the switch, I had a read through #3284 but didn't find anything about ntf, is there another issue for me to get a little context @virtuoushub? 

> does so in a way that does not result in the same file/directory output.

Sorry not quiet following this last bit.

**Comment by virtuoushub** [comment]
> I've had a quick read of ntf and had gathered that it didn't do the zipping.
> 
> I'm a bit lost on the motivation for the switch, I had a read through #3284 but didn't find anything about ntf, is there another issue for me to get a little context @virtuoushub?

@thedavidprice has more context around the motivation. 

> 
> > does so in a way that does not result in the same file/directory output.
> 
> Sorry not quiet following this last bit.

The file structure in the zip resulting from calling `yarn zip-it-and-ship-it api/dist/functions/ api/dist/zipball` ( https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/aws-providers/serverless.js#L26 ) is different than that of calling something like `yarn nft build api/dist/functions/*.js` ( https://github.com/redwoodjs/redwood/pull/3723/commits/ecdc3991c5c7b1e988f68cd022ae2e349709b62d#diff-a0a53ebaab71833b284633ec8c0b56ea298728256643688a60041ce7234cb96b )

**Comment by thedavidprice** [comment]
After Redwood builds the API into a /dist, the /dist/functions need to be bundled (and compressed) as preparation to deploy to AWS Lambdas. `nft` is, simply, better at this process in terms of performance (smaller bundles) and stability (much smarter dependency tracing; ZiSi uses ESBuild, which doesn't do polyfills and is a weird choice for this application imho). 

I'm confirming "how to" with Vercel, but my understanding is that you use it like this (after running `yarn rw build`):
`npx @vercel/nft build api/dist/functions/graphql.js`

It creates it's own /dist specific to the function. So next steps would be to:
- compress the dist
- run process for next function

Maybe too much to include in step one mvp, but could use research to finalize decision.

**Comment by thedavidprice** [comment]
Ah, relaying this info:
> Running nft as a CLI isn't enough, it needs to be used programmatically so you can output a functions-manifest.json as well as a nft.json file with the traced file paths

https://vercel.com/docs/file-system-api#configuration/bundling

**Comment by thedavidprice** [comment]
Also for reference:
https://github.com/vercel/vercel/blob/main/packages/plugin-node/src/index.ts

**Comment by virtuoushub** [comment]
@thedavidprice does using `ncc` make more sense https://www.npmjs.com/package/@vercel/ncc since it does the bundling?

**Comment by Irev-Dev** [comment]
Doesn't `ncc` also transpile, which we don't need since we're trying to package already built files in dist?

**Comment by Irev-Dev** [comment]
Since we're auditing the existing integration, here's a thought.

Instead of the serverless.yml template being a template literal/string, would it not be better to have it as a data structure (js object) that's than stringified as yml. 

Pros:
It would be good if rw users could run `yarn rw setup deploy aws-serverless` again after they add a new function and not have it override they're existing serverless.yml completely. Instead the existing yml could be read as an js object, merged with the template output and written back again.

Cons:
Adding helpful comments within the yml file become difficult/messy.

**Comment by Irev-Dev** [comment]
I've done a little work with `nft`, by writing the following node script that I've simply being running from inside my test project. I thought I was taking a pretty naive approach and thought there would be perf problems but just taking some precautions to make sure that promises arn't awaited in chains when they don't need to be is working okay,


compare to `$(npm bin)/zip-it-and-ship-it ./api/dist/functions ./api/dist/test-zip`
which takes about 18s and makes a 39mb file

Where as my script method with nft takes about 16s and makes a 30mb file
The above is with compression level 5, going to level to makes it take 11 seconds more but removes 1mb

Like I said run from the functional test project, so testing is just quickly looking to see the output file structure looks right, I haven't tried deploying the resulting zip.

What do we think, does this look like a sane approach? should I look to add this to the framework?

```javascript
const path = require('path')
const { nodeFileTrace } = require('@vercel/nft')
const fse = require('fs-extra')
const archiver = require('archiver')

const startTime = new Date().valueOf()

function zipDirectory(source, out) {
  const archive = archiver('zip', { zlib: { level: 5 } })
  const stream = fse.createWriteStream(out)

  return new Promise((resolve, reject) => {
    archive
      .directory(source, false)
      .on('error', (err) => reject(err))
      .pipe(stream)

    stream.on('close', () => resolve())
    archive.finalize()
  })
}

const packageFunction = async (functionFile) => {
  const { name } = path.parse(functionFile)
  const { fileList } = await nodeFileTrace([functionFile])
  const copyPromises = Array.from(fileList).map((file) =>
    fse.copy('./' + file, `./api/dist/zipball/${name}/${file}`)
  )
  copyPromises.push(
    fse.outputFile(
      `./api/dist/zipball/${name}/${name}.js`,
      `module.exports = require('${functionFile}')`
    )
  )
  await Promise.all(copyPromises)
  await zipDirectory(`./api/dist/zipball/${name}`, `./api/dist/zipball/${name}.zip`)
  await fse.remove(`./api/dist/zipball/${name}`)

  return
}

async function packageAllFunctions(files) {
  const packagePromises = files.map((file) => packageFunction(file))
  await Promise.all(packagePromises)
  console.log('done took this many ms', new Date().valueOf() - startTime)
}

const files = ['./api/dist/functions/graphql.js']

packageAllFunctions(files)
```

**Comment by thedavidprice** [comment]
@Irev-Dev I do think that looks viable! Those performance differences are about what I expected (although when I build+bundle my test project to Vercel, using NFT, I see a size of 17mb). More importantly, NFT has been more robust from Redwood version to version regarding accurate dependency resolution and building. We keep running into cases where ZiSi doesn't add required dependencies so we end up having to add them directly. 

I'm no expert here, but some quick thoughts if you decide to move this forward:
- does this process create the files functions-manifest.json as well as a nft.json?
- we won't want to add those deps to Redwood packages; instead we'll want to install them when setup is run

Thanks!

**Comment by thedavidprice** [comment]
I've update the [OP](https://github.com/redwoodjs/redwood/issues/3686#issue-1042902564) with content from #3284

**Comment by thedavidprice** [comment]
@Irev-Dev @virtuoushub @dac09 @jtoar @mnapoli
re: PRs #3755 and #3782

Hi All! I'm attempting to re-consolidate this high priority effort in order to:
- get everyone back on the same page
- revisit the overall plan and to-do list
- break next steps into smaller implementation chunks

@mnapoli your help has been invaluable! Now that we have your answer and direction, I wanted to make sure all the guidance you've given is appropriately consumed and implemented. (As it's now been scattered across a few efforts.)

Here are my suggestions about the next steps and how to organize. However, do now I’ll be going on holiday vacation starting mid-next week, so I'm handing off this to Core Team leads @dac09 and @jtoar Please look to them for the final decisions and ongoing process review.

### Working Branch
I've update the existing PRs in process to target a new branch:
- [serverless-deploy-3686](https://github.com/redwoodjs/redwood/tree/serverless-deploy-3686)

Please work against this branch until everything in this tracking issue is resolved. Then we will PR this branch into `main`

### Project Plan
@dac09 @jtoar Could you both consolidate the plan and to-dos based on:
- My [OP comments (audit)](https://github.com/redwoodjs/redwood/issues/3686#issue-1042902564)
- Comments/decisions in #3782
- Comments/decisions in #3755

@mnapoli Once the plan has been consolidated, could you please review and finalize it?

### Next steps: #3782 #3755
I'll let you all determine whether to get these into the new branch or refactor the work into PRs with smaller/specific scope.

To me it looks like #3782 might be ready to go in.

---

Thank you all! This is really excited to see moving forward. Grateful for the team effort.

**Comment by mnapoli** [comment]
Yes, happy to review. Ping me when you need it!

**Comment by Irev-Dev** [comment]
Sorry for the slow response.

Thanks for organising @thedavidprice.

The PR I had open has been [merged](#3782) into the feature branch (thanks @dac09) so now I don't have anything outstanding. Once the Todos have been figured out if there's a way for me to work on a chunk that won't conflict with other's work let me know.

**Comment by dac09** [comment]
@Irev-Dev welcome to crerate PRs pointing at `serverless-deploy-3686`. We can collect all the work related to serverless here, and then merge it into the main branch once its ready. 

I'm keeping the issue updated with what needs to be done, or maybe create a separate project board. What do you think of looking at the sls v3 cli? 

@mnapoli I wonder if you could provide a bit of guidance on the best way to deploy the site would be great, options I currently see
**a) use serverless-lift with the static-website construct**
only thing I'd need guidance with is how can I pass the url for the lambda i.e. the url for the graphql function that we are deploying

**b) use a combination of cloudfront and serverless-finch**
this will probably achieve the same result as serverless lift, but I have the same issue - I don't know how to point it to the graphql function

**Comment by Irev-Dev** [comment]
Yup cool @dac09, I'll have a look into v3 after the holiday season.

**Comment by thedavidprice** [comment]
^^ @virtuoushub want to make sure you see these comments

**Comment by mnapoli** [comment]
Hey, sorry @dac09  I'm catching up:

> @mnapoli I wonder if you could provide a bit of guidance on the best way to deploy the site would be great, options I currently see
>
> a) use serverless-lift with the static-website construct
only thing I'd need guidance with is how can I pass the url for the lambda i.e. the url for the graphql function that we are deploying
>
> b) use a combination of cloudfront and serverless-finch
this will probably achieve the same result as serverless lift, but I have the same issue - I don't know how to point it to the graphql function

Do you mean passing the URL of the GraphQL API to the frontend website?

If that's the case, in both scenarios I think it will not be easy. The reason is that you (probably) want to pass the URL of the deployed API to the build script of the frontend website. And the "build" step will happen before deploying (so there's no guarantee the URL even exists at this point)… I've tried to find solutions for that in Lift so far by the way, but there is no built-in feature for that yet: https://github.com/getlift/lift/issues/62

I'm not sure how you build the static website, but maybe what you could do is:

- Fetch the API URL
  - That could be done by calling the CloudFormation API to get the CloudFormation `HttpApiUrl` output
  - Or that could be done by running `serverless info --verbose` and parse the output (a bit ugly, maybe we need to provide a helper for that?)
    <img width="1009" alt="Screen 2022-01-04 10-10" src="https://user-images.githubusercontent.com/720328/148040838-c2abb77a-44da-4141-8aa6-b1c22ddbe119.png">
   - If the API isn't deployed yet, then ignore the "error"
- Then build the static website and pass the URL as an environment variable to the build script (e.g. `API_URL=...`). Pass an empty string if the API isn't deployed yet (or better, the first time always deploy the API first?)
- Then run `serverless deploy`

**Comment by dac09** [comment]
Thanks @mnapoli - I have another idea/suggestion for lift. You've done a tremendous job with lift, was very straightforward 🚀 I'm going to add it to the sls config we generate.


Another question for you:

I used a `static-website` construct to deploy to `https://xxxx.cloudfront.net/` but I would like `https://xxxx.cloudfront.net/api` to forward to the deployed `HttpApiUrl`. I understand I'd have to follow the steps you outlined above to actually get the HttpApiUrl, but is there an easy way I could setup that proxy with cloudfront? Maybe a new construct?

**Comment by dac09** [comment]
Hey folks, @cannikin and I have been hard at work getting the whole process setup. I never figured out how to do a proxy with cloudfront, but the web side now deploys!

We also added a special `--first-run` flag when you run `yarn rw deploy serverless` to make sure it deploys api first, grabs the api url and then deploys the web side with the updated api url! 

Please do take it for a spin if you get a chance, it'll be available on canary (upgrade your projects by running `yarn rw upgrade -t canary`)
