### ISSUE TITLE
[Tracking] VSCode IDE

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#3887]
Meta issue to keep track of all the issues related to the VSCode IDE:
 
- [ ] #1354
- [ ] #1950
- [ ] #1589
- [ ] #843
- [ ] #1660
- [ ] #1529
- [ ] #1478
- [ ] #970
- [ ] #943
- [ ] #1000
- [ ] #2040
- [ ] #2159
- [ ] #2511
- [ ] #2352
- [ ] #2344
- [ ] https://github.com/redwoodjs/redwood/issues/3246
- [ ] https://github.com/redwoodjs/redwood/issues/1257
- [x] https://github.com/redwoodjs/redwood/issues/936
- [ ] https://github.com/redwoodjs/redwood/issues/1438
- [ ] https://github.com/redwoodjs/redwood/issues/1456
- [x] https://github.com/redwoodjs/redwood/issues/3906
- [ ] https://github.com/redwoodjs/redwood/pull/3848
- [ ] https://github.com/redwoodjs/redwood/pull/3838

**Comment by jtoar** [comment]
See https://github.com/redwoodjs/redwood/pull/3848#issuecomment-996283741.

**Comment by jtoar** [comment]
We may continue development on the VS Code extension one day but going to close these for now as there's no definite timetable.
