### ISSUE TITLE
Clerk auth deployment fails on netlify 

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#4056]
Reported on discord

### Whats the issue?
After setting up clerk auth, netlify throws a _runtime_ error that the clerk sdk cannot be found

```
Error building context. Error: Exception in getAuthenticationContext: Cannot find module '@clerk/clerk-sdk-node'
Require stack:
- /var/task/node_modules/@redwoodjs/api/dist/auth/decoders/clerk.js
- /var/task/node_modules/@redwoodjs/api/dist/auth/decoders/index.js
- /var/task/node_modules/@redwoodjs/api/dist/auth/index.js
- /var/task/node_modules/@redwoodjs/api/dist/index.js
- /var/task/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js
- /var/task/node_modules/@redwoodjs/graphql-server/dist/index.js
- /var/task/api/dist/functions/graphql.js
- /var/task/graphql.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
 ```

### Things that have been checked
- [x] `@clerk/clerk-sdk-node` is present in api/package.json
- [x] yarn.lock file is updated

### Tasks

- [ ] Reproduce error deploying to netlify

**Comment by domvernon** [comment]
👋 Hi, I was the one who had the initial discussion with Danny. I am pleased to report I seem to have got this working, although with a bit of a workaround - not sure if this hints at something about how zip-it-ship-it works with the Redwood code. I added the following to my netlify.toml file:
```
[functions]
node_bundler="esbuild"
external_node_modules=["@magic-sdk/admin", "firebase-admin", "keyv", "@clerk/clerk-sdk-node"]
```
This is forcing those modules to be included in the bundled function. I tried just with `@clerk/clerk-sdk-node` but it would not build/bundle without those other modules.

**Comment by dac09** [comment]
Awesome thanks for reporting back @domvernon! I see what you've done here, because you're using the esbuild bundler in netlify, it's _not_ doing the zip-it-ship-it step. 

The problem with the esbuild step is that youll need to maintain that list of external modules. For example, if redwood adds a new provider which you don't use, your toml file will need an update. 

Were you receiving an error even without the node_bundler option in your netlify toml?

**Comment by domvernon** [comment]
yes, the default without `node_bundler` is the one that isn't working (`external_node_module` is only relevant for esbuild). I can see the difference in output when running `netlify build` locally.

Also, what do you mean it isn't doing the zip-it-ship-it step? I thought it was still doing it but just using esbuild as the bundler.

**Comment by jtoar** [comment]
I just tried to reproduce this and everything deployed successfully. @domvernon do you still need the workaround you mentioned on the latest version of Redwood?

**Comment by domvernon** [comment]
Unfortunately I moved on from Netlify in the end so don't know. Happy to to close this and if it comes up again at least there is this record.

**Comment by jtoar** [comment]
@domvernon will do, thanks!
