### ISSUE TITLE
Improvements to CONTRIBUTING Docs (tracking issue)

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#434]
- [x] **General proofreading:**  description of process and information -- does it make sense to a first-time reader and does it work when someone sets up from scratch
- [x] **"Running the Local Server(s)"** need more context/clarity. **I** understand what's going on because I have prior knowledge about what's going on. But for a first-time reader, I'm not convinced it's clear about where this section fits in. Note: maybe we can enhance the overview "Local development" a bit to provide more context and nomenclature.
- [ ] **Contributing and Windows:** currently we do not fully support Windows although we _have_ been working on it. Last we checked, our `build` and `lint` commands work on Powershell, but with the recent new tooling from #429 this may no longer be the case. The `test` script has known issues. See https://github.com/redwoodjs/redwood/pull/395
    - [ ] for now, we can borrow an example from Create React App and recommend Windows contributors use [Bash on Ubuntu for Windows](https://github.com/facebook/create-react-app/blob/master/CONTRIBUTING.md#tips-for-contributors-using-windows).
    > Note: the Create React App [CONTRIBUTING.md](https://github.com/facebook/create-react-app/blob/master/CONTRIBUTING.md) doc is a very good reference in general.
- [ ] **"CLI Package Development"** is out of place here. Where we are headed is that each package will have it's own README, e.g. "packages/cli/README.md", with information and instructions _specific_ to 1) how that package works and 2) how to contribute to that package.
    - [ ] at a minimum, have a starter README for each package with a description about what it does (if not already existing)
    - [ ] move the "CLI Package Development" section into the CLI package README
    - [ ] add a section to CONTRIBUTING with links to the README for each package

**Comment by jtoar** [comment]
> General proofreading: description of process and information -- does it make sense to a first-time reader and does it work when someone sets up from scratch

I've started a PR for this, but shied away from making any major organizational changes: #435.

> Where we are headed is that each package will have it's own README, e.g. "packages/cli/README.

This is the way to go! Can I move forward on this?

**Comment by thedavidprice** [comment]
**re: README per package**
Yes, please! Let's divide it up into two tasks. 
1) Audit existing and add stubs/placeholders where needed.  
2) Address each individual README specifically

**Comment by jtoar** [comment]
Opened #439 to address **General proofreading**.

**Comment by jtoar** [comment]
Circling back from #439; all edits from that issue are now in PR #435. Will direct attention there for a final review.

**Comment by webstackdev** [comment]
I should have referenced this issue in a PR I submitted. The PR is a draft and involves a pretty substantial reorganization of the contributing docs ([#2903](https://github.com/redwoodjs/redwood/pull/2903)). That PR moved from Icebox to Backlog a couple of days ago.

**Comment by thedavidprice** [comment]
This issue is old/stale. Closing and moving conversation to https://github.com/redwoodjs/redwood/issues/3092

**Comment by thedavidprice** [comment]
@webstackdev thanks again! Just wanted to make sure you saw where we are consolidating this effort. Lots of pieces in motion and felt like we were starting to waste people's time+effort.
