### ISSUE TITLE
Investigate Prisma issues due to client being generated in the api workspace

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#4605]
Prisma throws errors when trying to access models, in the seed scripts, exec scripts or services. 

```
Invalid `db.post.create()` invocation in
/Users/dac09/Experiments-28feb-1049/scripts/seed.ts:24:41

  21
  22 Promise.all(
  23   posts.map(async (post) => {
→ 24     const newPost = await db.post.create(
  The table `main.Post` does not exist in the current database 
```

### Diagnosis 
Looks like in yarn 1 workspaces, sometimes prisma will create the .prisma folder at one or more of the nested workspaces. Deleting the generated folder fixes the problem

So the migrations and generation produces the client in the root `node_modules/.prisma` but when running the api side code, it picks a _different_ prisma client, causing this error

In our case:
```
├── node_modules
│   ├── .prisma # 👈 this is good!
├── web
│   ├── node_modules
├── api
│   ├── node_modules
│   │   ├── .prisma  # 😨 whai?
```
Node version: v16.13.1
Yarn version: 1.23.0-20220130.1630 (set using yarn version classic)

### Tasks

- [x] Create reproduction repo for Prisma team
https://github.com/prisma/prisma/issues/12083
- [x] Make sure we run prisma commands in the correct cwd (#4604)
- [x] Diagnose which version of Prisma the issue was introduced in
Last known working version (in Redwood world) - Prisma 3.8.1 (Redwood v0.42.1)

**Comment by jvanbaarsen** [comment]
I can confirm this is also happening with yarn 3. I just created a brand new redwoodJS app, and ran into this problem as well.

**Comment by lyonusi** [comment]
I'm doing the tutorial and ran into this problem at _Getting Dynamic_ after `yarn rw prisma migrate dev`. Temporarily fixed by `rm -rf api/node_modules/.prisma`. Node 16.14, yarn 1.22, prisma 3.10.

**Comment by thedavidprice** [comment]
@lyonusi Gah, that's so frustrating. So sorry. This is a particularly annoying bug... 😖

## Update
Prisma is moving forward with a fix. The tests on a pre-release version are looking good here https://github.com/redwoodjs/redwood/pull/4850

Need to wait for a Prisma patch or minor release, then we'll get this merged into a Redwood release. Soon!

**Comment by thedavidprice** [comment]
Closed by
- #4914 

I'll patch RC and release `rc.final.2`
