### ISSUE TITLE
[RFC]: Quality of life additions for Storybook integration

### ISSUE THREAD

**Issue by virtuoushub** [redwoodjs/redwood#5269]
- [ ] Allow for complete overriding of Storybook config, rather then merging #6854
    - [ ] Better understand which Storybook defaults we are overridding - e.g. [`sbConfig.module.rules` in `webpackFinal`](https://github.com/redwoodjs/redwood/blob/main/packages/testing/config/storybook/main.js#L123), [`typescript.reactDocgen`](https://github.com/redwoodjs/redwood/issues/5052)
- [ ] Allow for better independent deployment of Storybook artifacts  #5534
- [ ] Support CSF 3.0 ( see: https://storybook.js.org/blog/component-story-format-3-0/ / https://github.com/redwoodjs/redwood/pull/5979#issuecomment-1193421332 )
- [ ] Add testing to CLI command (snapshot[s]?) to better capture merged webpack output ( see: https://github.com/redwoodjs/redwood/pull/5592 )
- [ ] Support hot module update #4717 - [ [list of TODOs](https://github.com/redwoodjs/redwood/issues/4717#issuecomment-1160666753) ]
- [ ] Add ability for stories around "stock" Redwood components (e.g. `NotFoundPage`, `SignupPage`, `LoginPage`, ...) to be generated ( https://github.com/redwoodjs/redwood/issues/6518 )
- [ ] provide better CLI mappings ( e.g. `--no-open` suggestion \[ https://github.com/redwoodjs/redwood/issues/6062 \] )
- [x] Support merging `webpackFinal` / `managerWebpack` #5957 
  - [x] Support `async` fields in Storybook configs ( see: https://github.com/survivejs/webpack-merge#limitations )
- [x] Update generators to add `args` so docs addon works as expected ( see: https://github.com/storybookjs/storybook/issues/8104#issuecomment-932279083 )
  - #5979

---

### Context:

From @dthyresson 

> Noticed that Storyboook does not render the NotFoundPage. I was customizing one and wanted to preview. ...

> We may want to add one to the template. ...

This lead to a deep dive into the ways in which the Storybook integration can be improved.

---

### Prior art:

#2064

---

### Honorable mention
- [ ] Support "Storyshots" #5907

**Comment by virtuoushub** [comment]
closing as stale. feel free to re-open if someone else is interested.
