### ISSUE TITLE
Tracking issue for next major (v3)

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#6064]
We're looking to get another major out soon. The Node.js ecosystem is somewhat forcing our hand with this as many packages are dropping support for Node.js 12, which is what Redwood's build process currently targets. We do run all our CI on Node.js 14 and 16, so we actually have a lot of confidence that Redwood won't break. But Node.js 12 isn't the even the maintenance LTS anymore, so it's high time that we bump the version that Redwood's build process targets too. Besides, there's a few things other things we'd like to release.

Below is a working list of the breaking changes that we plan on including in the next major:

- [ ] https://github.com/redwoodjs/redwood/pull/5600
- [ ] https://github.com/redwoodjs/redwood/pull/5903
- [ ] https://github.com/redwoodjs/redwood/pull/5924
- [ ] https://github.com/redwoodjs/redwood/pull/5330
- [ ] https://github.com/redwoodjs/redwood/pull/5405
- [ ] https://github.com/redwoodjs/redwood/pull/5726

**Comment by Gresliebear** [comment]
Implement GrapQL-Scalar for more prisma types access https://github.com/redwoodjs/redwood/issues/5841
