### ISSUE TITLE
Prisma improvements

### ISSUE THREAD

**Issue by schickling** [redwoodjs/redwood#9]
- [ ] Add integrated seeding workflow [blocked by https://github.com/prisma/prisma2/issues/9]
- [x] Easy switching between SQLite (for local dev) and another DB (for prod) [blocked by https://github.com/prisma/prisma2/issues/265]
- [x] Get rid of `packages/photon` directory [blocked by https://github.com/prisma/prisma2/issues/664]
- [x] Allow specification of `schema.prisma` path [blocked by https://github.com/prisma/prisma2/issues/225]
- [ ] Default env vars [blocked by https://github.com/prisma/prisma2/issues/222]

**Comment by thedavidprice** [comment]
@cannikin @peterp 

This Issue + list happened before my time. Wondering which of these are still a priority for us. If so, we should make sure to communicate accordingly to the Prisma team — I believe they’re trying to finalize what’s to be included in final v2 release (if they haven’t already).

FYI: per recent conversation with Jan, the `schema.prisma` support for using env vars with provider is on their radar at this time: https://github.com/prisma/prisma2/issues/1487

**Comment by peterp** [comment]
I think most of these are now covered.
