### ISSUE TITLE
Deployment Targets tracking issue

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#947]
We want to deploy to all the things. Write once, learn once, run everywhere.

# Serverless Function Providers

- [x] Netlify Status: working
- [x] Vercel: Status working
- [x] AWS Lambda: Status [working](https://github.com/redwoodjs/redwood/issues/431#issuecomment-670853186), need to document steps and figure out how to make it seamless
- [ ] Azure functions Serverless
- [ ] Google Cloud Functions https://github.com/redwoodjs/redwood/pull/1225 (Needs help!)
- [x] Render.com
- [ ] Docker (vanilla) and Kubernetes

# Others

- [x] Self hosted: Status working, but need to remove the "watch" code from the "dev-server" and come up with a way to restart a long running node_process.

**Comment by hemildesai** [comment]
Hey @peterp, I'm interested in deployments and have some experience with infrastructure and cloud providers. So I'd love to get involved and contribute towards adding multiple deployments to redwood. Let me know if there are any such opportunities.

**Comment by peterp** [comment]
@hemildesai Amazing, let's chat! Could you ping me on Discord?

**Comment by thedavidprice** [comment]
@hemildesai @bcoe @kimadeline @peterp 

Hi all! I'm continuing the conversation we started yesterday (minus Peter) about the current work implementing...

1. the Serverless Framework as well as 
2. the Redwood Container POC... 

...can be leveraged to plan deployment support on Azure (Kim-Adeline) and Google Cloud (Ben Coe).  

What's the best way to move this discussion forward if not here in an Issue? I'd be happy to help set up a time to discuss live if preferred.

--

So excited about this it gets the DoubleRocket™ sign off 🚀🚀

**Comment by kimadeline** [comment]
I'm good with anything: here, GH issue, Discord, Slack, forum, ~~Linkedin DMs~~...

Side note: I've been tinkering [Azure Static Web Apps](https://azure.microsoft.com/en-us/services/app-service/static/), which would not only host the API side (via Azure Functions), but also the front-end. I'm sure adding support for functions-only would be relatively close though.

**Comment by thedavidprice** [comment]
Update: Peter and I connected about this yesterday. Near-term priority for him is TypeScript and then he'll get back to the containerization work. Once he's "ready to demo/discuss" containers, that will be the trigger for me to schedule a real-time meeting for us. 

Sound good?

**Comment by bcoe** [comment]
👋  hello, acknowledging that I've seen this thread.

Since my initial spike on this work, I've been using [firebase hosting](https://firebase.google.com/docs/hosting). It seems like it would be ideal for running redwood on Google Cloud:

1. you deploy the react app to a CDN.
2. you deploy containers to Cloud Run (which is a platform for running arbitrary Docker containers).

**Comment by peterp** [comment]
@bcoe Cool - I have a proof of concept that puts RW's API in a container for AWS Fargate. We're not far off at all.

**Comment by andrew-hwahin** [comment]
Looking forward to deploying to Azure functions Serverless 😁

**Comment by viperfx** [comment]
Hey all - just wanted to add my 2cents and experience with self hosting. 

I had trouble using the netlify auth provider under a self hosted setup. I am using the api-server under pm2. 

Ive started a thread on the forums here - https://community.redwoodjs.com/t/redwood-api-server-context-creation-failed/1493

Is this a known issue or is there something going wrong unexpectedly? [I did notice that netlify auth is handled differently in production.
](https://github.com/redwoodjs/redwood/blob/53349fd121f9198a8fdb5c0217cec8c4f8b6badd/packages/api/src/auth/decoders/netlify.ts#L11)


Let me know if you need more info.

**Comment by andrew-hwahin** [comment]
> Side note: I've been tinkering [Azure Static Web Apps](https://azure.microsoft.com/en-us/services/app-service/static/), which would not only host the API side (via Azure Functions), but also the front-end. I don't think function-only deployment would be too far off though.

Do you happen to know any resources to deploy Redwood using Azure Functions? 🙏

**Comment by kimadeline** [comment]
Hi @andrew-hwahin, 

Azure Functions aren't supported by Redwood yet, so I don't have any documentation off the top of my head. However, if you're up for some tinkering, the Apollo docs have a section on [deployment using Azure Functions](https://www.apollographql.com/docs/apollo-server/deployment/azure-functions/), which may be a solid starting point.

**Comment by thedavidprice** [comment]
Another idea --> we are using [Serverless Framework](https://serverless.com) to handle direct deployment to AWS Lambdas. @andrew-hwahin if you take a look under the hood a how that's working with Redwood, you could most likely get it working for Azure using Serverless Framework.
- https://www.serverless.com/framework/docs/providers/azure/
- https://redwoodjs.com/docs/deploy#aws-serverless-deploy
- Setup AWS Deploy: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/deploy/providers/aws_serverless.js
- Deploy to AWS: https://github.com/redwoodjs/redwood/tree/main/packages/cli/src/commands/deploy/api/providers

**Comment by ajcwebdev** [comment]
@t-eckert laid a good chunk of groundwork hacking on Azure Functions with Redwood and @thedavidprice also provided some helpful notes [over on Forums](https://community.redwoodjs.com/t/deploy-to-azure-static-web-apps/1973/). I wanted to make sure that work gets in this issue and hopefully help nudge this along, I know Thomas has some ideas for next steps.

## Notes from Thomas on his own project with Azure Functions

> My current project has a static site front end and Azure Functions backend. [Here is the repo](https://github.com/t-eckert/open-api-editor).
>
>My approach so far is to deploy HTTP functions and call to them using code in the “actions” directory of my React code. I’m really taking the Grokking Simplicity book to heart there. [Here it is deployed](https://www.openapieditor.com/).
>
>But it doesn’t do anything yet. And I have a bug in the sign in code that causes a 500. Behind the scenes, they use something called Oryx to build. It’s what’s used on all Linux App Service apps (static or otherwise).
>
>It’s open source so you can [read through it if you need to](https://github.com/microsoft/Oryx), but you can write a config to tell it how to set up your app. It will detect the runtime based on the files and then (for node) run npm build. It would also run through a similar set of commands for a Python, C#, Java, etc. app.

## Notes from Thomas after a night of exploratory spelunking with Azure Functions and the Redwood API

>I just got off of a call with @ajcwebdev where we tried to replace the Lambda service with Azure Functions. We made a bit of progress, but got stuck on (a) calls being proxied through the host port when running locally and (b) standing up the GraphQL server in an Azure Function. What you have set up for the frontend is awesome. Super impressed on you getting that up and going.
>
>As for running the service with Azure Functions replacing the Lambdas, it’s definitely possible. I would need a better understanding of how Redwood proxies calls to the API when it’s running locally and then I could work out how to fully replace the API layer. I’m curious is there is a way to wrap the existing Lambdas so that they can be executed as Azure Functions (I don’t know if this is possible).

>If we got a group together to try and work this out, I would be happy to be a part of it. We would definitely need to have a core dev to speed up the process. I have a lot of stupid questions to ask. Ultimately, if we wanted Redwood to be easily deployable to Azure, we would need to create some alternate API template that would produce Azure Functions instead of Lambdas. It would be useful to gauge interest on that as it’s a sizable investment.

## Notes from David on hangups, potential next steps, and reference material:

>Hi All! Excited to see people working on this. There’s more under the hood going on, which means this isn’t exactly a plug-n-play. I’m no expert on Azure either. So for now attempting to dump a lot of details to help others connect some dots. I do not believe this is just a matter of replicating [Redwood’s API Build process](https://redwoodjs.com/docs/builds) in a way that organizes functions specific to Azure.
>
>### Redwood’s API uses Apollo Server Lambda
>
>If you look at the Redwood API package, you’ll see the GraphQL Server is apollo-server-lambda
>
>* [Apollo Docs for Lambda](https://www.apollographql.com/docs/apollo-server/deployment/lambda/)
>* [API package.json](https://github.com/redwoodjs/redwood/blob/main/packages/api/package.json)
>* [Used in graphql.ts](https://github.com/redwoodjs/redwood/blob/main/packages/api/src/functions/graphql.ts)
>* [Used in makeMergedSchema.ts](https://github.com/redwoodjs/redwood/blob/main/packages/api/src/makeMergedSchema/makeMergedSchema.ts)
>
>### Apollo has a distinct package for Azure Functions
>
>Unfortunately, AWS and Azure functions are not equivalent:
>* [Apollo Azure Functions Doc](https://www.apollographql.com/docs/apollo-server/deployment/azure-functions/)
>
>I quickly dug into the code for each to verify there’s more going on than just naming:
>* [apollo-server-lambda](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-lambda)
>* [apollo-server-azure-functions](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-azure-functions)
>
>:frowning_face:
>### Using Apollo Azure package
>
>I believe the “right” way to do this will be to make the `apollo-server` swappable in Redwood’s API. As an experiment, one could fork Redwood and patch the API package to use Azure instead of AWS version.
>
>### Adding a “Wrapper”?
>
>Maybe another POC path forward could be creating another package like [@redwoodjs/api-server](https://github.com/redwoodjs/redwood/tree/main/packages/api-server), which effectively uses Express to server Lambda Functions. Take a look at [awsLambda.ts](https://github.com/redwoodjs/redwood/blob/main/packages/api-server/src/requestHandlers/awsLambda.ts) to see how Peter does this.
>
>I’m skeptical of this approach (admittedly very naive). Offering it as it might influence other ideas.
>
>### Using Azure Function Containers
>
>This is likely the path of least resistance (although I don’t know how it compares to just Azure Functions).
>* [Azure Function Containers Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/function-app-container?view=azure-devops&tabs=yaml)
>
>Put the Redwood API in a container using api-server (self-hosting method). Might be a brutal start-up, but viable with tools we have right now.

**Comment by t-eckert** [comment]
# 👋🏻

Like @ajcwebdev mentioned, I am working on hacking together a solution to run Redwood on Azure using Azure Functions. My approach so far is to vendor the `API` package into a Redwood project: [`redwood-azure`](https://github.com/t-eckert/redwood-azure) and replace the code that generates Lambdas with code that generates Azure Functions. I have started this process by unpacking and attempting to grok some of the `API` package in [my own fork](https://github.com/t-eckert/redwood/tree/t-eckert/bluesky) of this repo. The branch is called "bluesky" because "Azure" ha ha.

If I can get my hacked and vendored API package working in the Redwood solution, then I can approach the core maintainers with questions of architecture and implementation. AFAIK, there will have to be some flag to tell the API package whether it should compile to Azure Functions or Lambdas. With the final implementation, I want to limit the variance between the Lambda producing code and the Functions producing code. This will require me to gain a better understanding of the `API` package.

Still early days.

**Comment by ajcwebdev** [comment]
## Notes on handling events with AWS Lambda vs Azure Functions

AWS Lambda uses a straightforward event-driven architecture that does not depend on event sources. A function:
* Receives a JSON object as input
* Returns another JSON as output

The event type defines the schema of those objects, which are documented and defined in language SDKs. Each service that integrates with Lambda sends data to your function in JSON as an event. The structure of the event document is different for each event type, and contains data about the resource or request that triggered the function. Lambda runtimes convert the event into an object and pass it to your function.

With Azure Functions, a trigger is an event that the function listens to. The function may have any number of input and output bindings at the time of processing. It can read a document from Cosmos DB and send a queue message via binding configuration. If you want event sourcing with Lambda you need to grant the Lambda permission.

For services that generate a queue or data stream in Lambda, you create an [event source mapping](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventsourcemapping.html) and grant Lambda permission to access the other service in the [execution role](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html). An event source mapping is an AWS Lambda resource that reads from an event source and invokes a Lambda function. Lambda reads data from the other service, creates an event, and invokes your function. You can use event source mappings to process items from a stream or queue in services that don't invoke Lambda functions directly.

## Notes on HTTP integration with AWS Lambda vs Azure Functions

AWS Lambda listens to HTTP traffic many different ways:
* [Lambda proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html) is an API Gateway [API integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/setup-http-integrations.html) type that allows you to integrate an API method with a Lambda function.
* You can use a Lambda function to process requests from an [ALB](https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/) with [ELB](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html) by invoking your Lambda function synchronously with an event that contains the request body and metadata.
* [HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html) send requests to AWS Lambda functions or to any routable HTTP endpoint.

Azure Functions, on the other hand, come with [HTTP triggers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger) for integrating HTTP traffic.

## Deploying Apollo Server with Azure Functions

If we look at the [Apollo Server example with Azure Functions](https://www.apollographql.com/docs/apollo-server/deployment/azure-functions/) we'll see it begins by using a template called [Http Trigger](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/HttpTrigger-JavaScript).

### function.json

This binding requires an HTTP trigger and allows you to customize the response associated with the trigger's request. The trigger input type is declared as either `HttpRequest` or a custom type. If you choose `HttpRequest`, you get full access to the request object. By default when you create a function for an HTTP trigger, the function is addressable with a route.

```json
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
          "get",
          "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

### metadata.json

```json
{
  "defaultFunctionName": "HttpTrigger",
  "description": "$HttpTrigger_description",
  "name": "HTTP trigger",
  "language": "JavaScript",
  "trigger": "HttpTrigger",
  "category": [
    "$temp_category_core",
    "$temp_category_api"
  ],
  "categoryStyle": "http",
  "enabledInTryMode": true,
  "userPrompt": [
    "authLevel"
  ]
}
```

### index.js

For a custom type, the runtime tries to parse the JSON request body to set the object properties. The [HTTP output](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-output) binding responds to the HTTP request sender.

```javascript
module.exports = async function (context, req) {
  context.log('JavaScript HTTP trigger function processed a request.');

  const name = (req.query.name || (req.body && req.body.name));
  const responseMessage = name
    ? "Hello, " + name + ". This HTTP triggered function executed successfully."
    : "This HTTP triggered function executed successfully.";

  context.res = {
    body: responseMessage
  };
}
```

**Comment by thedavidprice** [comment]
@jtoar have you organized all the Issues and PRs related to Deployment Targets? I think this is going to become my personal project post v1-rc.0. Things like:
- GCP PR
- vanilla Dockerfile (maybe with Docker Compose; maybe with Kubernetes)
- so many other outstanding...

**Comment by jtoar** [comment]
@thedavidprice there's no aggregate issue or project card for it yet but I can definitely start one and put it in the "RC Queue" for you!

**Comment by thedavidprice** [comment]
@thedavidprice yes, please! Or make me do it. I just didn't want to double up.

**Comment by jtoar** [comment]
Our updated minimum requirements for v1:

- [ ] AWS (API: serverless and/or fargate; Cloudfront)
- [ ] GCP
- [ ] Docker: performant production deployment; local dev via Compose

@thedavidprice I took this list from the card in our project board: https://github.com/redwoodjs/redwood/projects/20#card-69333287. Let me know if you think it needs any tweaking.

**Comment by jtoar** [comment]
Closing this as it no longer reflects our current priorities; see:
- https://github.com/redwoodjs/redwood/issues/2874
- https://github.com/redwoodjs/redwood/pull/5027
